version: '3.9'
services:
    server:
        build: 
            dockerfile: Dockerfile
            context: ./OPA
        ports: 
        - 8181:8181 
    client: 
        build: 
            dockerfile: Dockerfile
            context: ./google_auth
        ports: 
        - 3000:3000
       

        
