version: '3.9'
services:
    server:
        build: 
            dockerfile: Dockerfile
            context: ./OPA
        ports: 
        - 8181:8181
        networks:
        - opa_network  
    client: 
        build: 
            dockerfile: Dockerfile
            context: ./google_node
        ports: 
        - 3000:3000
        networks:
        - opa_network

networks:
  opa_network:
    external: true

        
